(() => {
  const URL = 'https://luygurjqpfgqnejtoihh.supabase.co';
  const KEY = 'sb_publishable_vAjSddEW_E6gDxQE2E5saQ_opTxJzdD';
  let sb, session, requests = [], selectedRequest, language = localStorage.getItem('dlg-language') || 'en';
  const labels = {contracts:{en:'Contracts / negotiation',ka:'ხელშეკრულება / მოლაპარაკება'},ai:{en:'AI, data and compliance',ka:'AI, მონაცემები და შესაბამისობა'},product:{en:'Digital product',ka:'ციფრული პროდუქტი'},georgia:{en:'Georgia market entry',ka:'საქართველოში საქმიანობა'},ongoing:{en:'Ongoing legal support',ka:'მიმდინარე იურიდიული მხარდაჭერა'}};
  const statuses = {submitted:{en:'SUBMITTED',ka:'გაგზავნილია'},reviewing:{en:'IN REVIEW',ka:'მიმდინარეობს შემოწმება'},in_progress:{en:'IN PROGRESS',ka:'მიმდინარეობს მუშაობა'},waiting_for_client:{en:'YOUR INPUT',ka:'თქვენი პასუხია საჭირო'},completed:{en:'COMPLETED',ka:'დასრულებულია'},closed:{en:'CLOSED',ka:'დახურულია'}};
  const $ = (s) => document.querySelector(s), $$ = (s) => [...document.querySelectorAll(s)];
  const say = (en,ka) => language === 'en' ? en : ka;
  const esc = (v) => String(v || '').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const date = (v) => new Intl.DateTimeFormat(language === 'en' ? 'en-GB' : 'ka-GE',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v));
  function translate(){ document.documentElement.lang=language; $$('.lang-button').forEach((b)=>b.classList.toggle('active',b.dataset.language===language)); $$('[data-en]').forEach((e)=>{if(!e.dataset.ka)e.dataset.ka=e.textContent;e.textContent=language==='en'?e.dataset.en:e.dataset.ka}); $$('[data-en-placeholder]').forEach((e)=>e.placeholder=language==='en'?e.dataset.enPlaceholder:''); }
  $$('.lang-button').forEach((b)=>b.onclick=()=>{language=b.dataset.language;localStorage.setItem('dlg-language',language);translate();renderRequests();if(selectedRequest)renderDetail(selectedRequest)});
  function authError(message){const e=$('[data-auth-error]');e.textContent=message;e.hidden=false}
  function view(auth){$('#login-view').hidden=auth;$('#dashboard-view').hidden=!auth}
  $('[data-google-login]').onclick=async()=>{if(!sb){authError(say('The authentication service is still loading. Please refresh the page.','ავტორიზაციის სერვისი იტვირთება. გთხოვთ, განაახლოთ გვერდი.'));return}const r=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/client/'}});if(r.error){console.error('Google OAuth error',r.error);const detail=r.error.message?' '+r.error.message:'';authError(say('Google sign-in could not start.'+detail+' If this continues, email digitallawgeorgia@gmail.com.','Google-ით შესვლა ვერ დაიწყო.'+detail+' თუ პრობლემა გაგრძელდა, მოგვწერეთ digitallawgeorgia@gmail.com-ზე.'))}};
  $('[data-logout]').onclick=async()=>{await sb.auth.signOut();session=null;view(false)};
  function user(){const u=session.user,m=u.user_metadata||{};$('[data-user-name]').textContent=m.full_name||m.name||u.email||say('Client','კლიენტი');$('[data-user-email]').textContent=u.email||'';const a=$('[data-user-avatar]');a.src=m.avatar_url||m.picture||'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="80" height="80"%3E%3Crect width="80" height="80" fill="%23a5e5f0"/%3E%3C/svg%3E';a.alt=m.full_name||m.name||''}
  async function load(){const r=await sb.from('dlg_client_requests').select('*').order('created_at',{ascending:false});if(r.error){$('[data-request-list]').innerHTML='<p class="empty-state">'+esc(say('Your requests could not be loaded. Please refresh the page.','მოთხოვნების ჩატვირთვა ვერ მოხერხდა. გთხოვთ, განაახლოთ გვერდი.'))+'</p>';return}requests=r.data||[];renderRequests();if(requests.length){selectedRequest=requests.find((x)=>x.id===selectedRequest?.id)||requests[0];renderDetail(selectedRequest)}}
  function renderRequests(){const list=$('[data-request-list]');$('[data-request-count]').textContent=requests.length;$('[data-stat-open]').textContent=requests.filter((x)=>!['completed','closed'].includes(x.status)).length;$('[data-stat-progress]').textContent=requests.filter((x)=>['reviewing','in_progress','waiting_for_client'].includes(x.status)).length;$('[data-stat-completed]').textContent=requests.filter((x)=>x.status==='completed').length;if(!requests.length){list.innerHTML='<div class="empty-state">'+esc(say('No requests yet. Start with a short brief.','ჯერ მოთხოვნები არ გაქვთ. დაიწყეთ მოკლე აღწერით.'))+'</div>';return}list.innerHTML=requests.map((x)=>{const st=statuses[x.status]||statuses.submitted;return '<button class="request-row '+(selectedRequest?.id===x.id?'active':'')+'" type="button" data-request-id="'+x.id+'"><div class="request-row-top"><span class="request-status '+x.status+'">'+esc(st[language])+'</span><span class="request-service">'+esc((labels[x.service_slug]||{en:x.service_label,ka:x.service_label})[language])+'</span></div><strong>'+esc(x.title)+'</strong><div class="request-row-bottom"><span>'+x.id.slice(0,8).toUpperCase()+'</span><span>'+date(x.created_at)+'</span></div></button>'}).join('');$$('.request-row').forEach((b)=>b.onclick=()=>{selectedRequest=requests.find((x)=>x.id===b.dataset.requestId);renderRequests();renderDetail(selectedRequest)})}
  async function renderDetail(item){const p=$('[data-detail-panel]');p.innerHTML='<div class="loading-state">'+esc(say('Loading activity…','აქტივობა იტვირთება…'))+'</div>';const r=await sb.from('dlg_client_request_events').select('*').eq('request_id',item.id).order('created_at',{ascending:true});const st=statuses[item.status]||statuses.submitted;const events=r.data||[];p.innerHTML='<div class="detail-header"><span class="request-status '+item.status+'">'+esc(st[language])+'</span><h2>'+esc(item.title)+'</h2><div class="detail-meta"><span>'+esc((labels[item.service_slug]||{en:item.service_label,ka:item.service_label})[language])+'</span><span>'+date(item.created_at)+'</span></div></div><div class="timeline">'+(events.length?events.map((e)=>'<div class="timeline-event"><small>'+esc(e.event_type.replaceAll('_',' ').toUpperCase())+' · '+date(e.created_at)+'</small><p>'+esc(e.message)+'</p></div>').join(''):'<p class="empty-state">'+esc(say('No activity has been added yet.','აქტივობა ჯერ არ დამატებულა.'))+'</p>')+'</div>'}
  function openModal(service){$('[data-request-modal]').hidden=false;if(service)$('[data-service-select]').value=service;$('[data-request-form] input[name=title]').focus()}function closeModal(){$('[data-request-modal]').hidden=true}
  $('[data-new-request]').onclick=()=>openModal();$('[data-close-modal]').onclick=closeModal;$('[data-request-modal]').onclick=(e)=>{if(e.target===$('[data-request-modal]'))closeModal()};document.onkeydown=(e)=>{if(e.key==='Escape')closeModal()};
  $('[data-request-form]').onsubmit=async(e)=>{e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f).entries()),b=f.querySelector('button[type=submit]'),s=$('[data-form-status]'),service=labels[v.service_slug]||labels.contracts;b.disabled=true;s.textContent=say('Sending…','იგზავნება…');const r=await sb.from('dlg_client_requests').insert({user_id:session.user.id,service_slug:v.service_slug,service_label:service.en,title:v.title.trim(),description:v.description.trim(),company_name:v.company_name.trim()||null,client_email:session.user.email||null,client_name:(session.user.user_metadata?.full_name||session.user.user_metadata?.name)||null,preferred_language:v.preferred_language,priority:'normal'}).select().single();if(r.error){s.textContent=say('Could not submit. Please check the form and try again.','გაგზავნა ვერ მოხერხდა. გადაამოწმეთ ფორმა.');b.disabled=false;return}await sb.from('dlg_client_request_events').insert({request_id:r.data.id,user_id:session.user.id,event_type:'submitted',message:say('Request submitted. We will review it and update this workspace.','მოთხოვნა გაიგზავნა. მას განვიხილავთ და ამ სივრცეში განვაახლებთ ინფორმაციას.')});f.reset();closeModal();s.textContent='';b.disabled=false;await load();selectedRequest=r.data;renderRequests();renderDetail(r.data)};
  async function boot(){translate();if(!window.supabase){authError(say('The client space is loading. Please refresh in a moment.','კლიენტის სივრცე იტვირთება. გთხოვთ, ცოტა ხანში განაახლოთ გვერდი.'));return}sb=window.supabase.createClient(URL,KEY);const wanted=new URLSearchParams(location.search).get('service'),r=await sb.auth.getSession();session=r.data.session;view(Boolean(session));if(session){user();await load();if(wanted)openModal(wanted)}sb.auth.onAuthStateChange(async(_,next)=>{session=next;view(Boolean(session));if(session){user();await load()}})}
  boot();
})();