// Shared public catalogue and delivery blueprints. No client information belongs here.
const pair=(ka,en)=>({ka,en});
export const practices=[
 {id:'product',slug:'digital-products',code:'01 / PRODUCT',name:pair('ციფრული პროდუქტები','Digital products'),summary:pair('აპლიკაციისა და სერვისის სამართლებრივი შეფასება — იდეიდან გაშვებამდე.','Legal review of apps and services, from concept to launch.'),audience:pair('პროდუქტის გუნდები, სტარტაპები, SaaS და მობილური აპლიკაციები.','Product teams, startups, SaaS businesses and mobile apps.'),scope:pair(['ბიზნესმოდელისა და პროდუქტის ფუნქციების შეფასება','მომხმარებლის რეგისტრაციის, თანხმობისა და გადახდის პროცესები','სარგებლობის პირობები, მონაცემები და ინტეგრაციები','გაშვებამდე მოსაგვარებელი საკითხების პრიორიტეტები'],['Business model and feature review','Onboarding, consent and payment journeys','Terms, data and integrations','Priorities before launch']),outputs:pair(['პროდუქტის სამართლებრივი რუკა','რისკებისა და ცვლილებების ცხრილი','პირობებისა და პროცესების შესწორებები'],['Product legal map','Risk and change register','Revised terms and processes']),questions:pair(['ვინ იყენებს პროდუქტს და რა პრობლემას აგვარებს ის?','როგორ იღებთ შემოსავალს და რა ეტაპზეა პროდუქტი?','რა მონაცემებსა და გარე სერვისებს იყენებთ?'],['Who uses the product and what does it solve?','How do you earn revenue and what stage is the product at?','What data and third-party services do you use?']),exclude:pair('პროგრამული კოდის შემოწმება და ტექნიკური ტესტირება ცალკე სპეციალისტის სამუშაოა.','Code review and technical testing require a separate specialist.')},
 {id:'fintech',slug:'fintech',code:'02 / FINANCE',name:pair('ფინტექი და გადახდები','FinTech & payments'),summary:pair('ბიზნესმოდელის შეფასება და ფინანსური რეგულირების მოთხოვნების განსაზღვრა.','Business model assessment and financial regulatory scoping.'),audience:pair('ფინტექკომპანიები, გადახდის აპლიკაციები, ბანკების ციფრული გუნდები და ღია ბანკინგის სერვისები.','FinTech companies, payment apps, bank digital teams and open banking services.'),scope:pair(['პროდუქტის სამართლებრივი კლასიფიკაცია','რეგისტრაციისა და ავტორიზაციის საჭიროების შეფასება','გადახდები, ციფრული საფულეები და ღია ბანკინგი','კლიენტის იდენტიფიკაცია, ინფორმირება და მომწოდებლებთან ურთიერთობა','ეროვნულ ბანკთან წარსადგენი დოკუმენტების მომზადების მხარდაჭერა'],['Product regulatory classification','Assessment of registration and authorisation requirements','Payments, wallets and open banking','Customer identification, disclosures and outsourcing','Support with National Bank submissions']),outputs:pair(['რეგულირების სფეროს შეფასება','მოთხოვნებისა და ხარვეზების რუკა','მოსამზადებელი დოკუმენტების სია და სამოქმედო გეგმა'],['Regulatory perimeter assessment','Requirements and gap map','Documentation list and action plan']),questions:pair(['ვინ იღებს, ინახავს ან გადარიცხავს მომხმარებლის თანხას?','ვის სახელით სრულდება ოპერაცია და ვინ არიან პარტნიორები?','რომელ ქვეყნებში ემსახურებით მომხმარებლებს?'],['Who receives, holds or transfers customer funds?','On whose behalf are transactions made and who are the partners?','In which countries are your customers?']),exclude:pair('პრუდენციული გამოთვლები, AML-აუდიტი და ფინანსური აუდიტი ცალკე თანხმდება შესაბამის სპეციალისტთან. რეგისტრაციის შედეგს მარეგულირებელი წყვეტს.','Prudential calculations, AML audits and financial audits require specialist scoping. The regulator determines registration outcomes.')},
 {id:'crypto',slug:'virtual-assets',code:'03 / DIGITAL ASSETS',name:pair('ვირტუალური აქტივები','Virtual assets & blockchain'),summary:pair('ვირტუალური აქტივის სერვისის შეფასება და საქმიანობის დასაწყებად მომზადება.','Assessment and readiness support for virtual asset services.'),audience:pair('ვირტუალური აქტივის გაცვლის, შენახვისა და გადაცემის სერვისები და ბლოკჩეინპროექტები.','Virtual asset exchange, custody and transfer services, and blockchain projects.'),scope:pair(['ბიზნესმოდელისა და აქტივის სამართლებრივი შეფასება','ვირტუალური აქტივის მომსახურების პროვაიდერის (VASP) მოთხოვნების ანალიზი','რეგისტრაციისთვის საჭირო დოკუმენტების მომზადების მხარდაჭერა','მმართველობა, მომხმარებლის პირობები და რისკების გამჟღავნება','AML/CFT-ის საკითხები და გარე მომწოდებლები'],['Business model and asset classification','Virtual asset service provider (VASP) requirements','Registration documentation support','Governance, user terms and risk disclosures','AML/CFT issues and outsourcing']),outputs:pair(['საქმიანობის შეფასება','მზადყოფნის შემოწმების სია','დოკუმენტებისა და გამოსასწორებელი საკითხების გეგმა'],['Activity assessment','Readiness checklist','Documentation and remediation plan']),questions:pair(['ცვლით, ინახავთ თუ გადასცემთ აქტივებს მომხმარებლის სახელით?','ვინ აკონტროლებს გასაღებებსა და მომხმარებლის აქტივებს?','სად არიან მომხმარებლები და რა პარტნიორები გყავთ?'],['Do you exchange, hold or transfer assets for customers?','Who controls keys and customer assets?','Where are your customers and which partners do you use?']),exclude:pair('სმარტკონტრაქტის ტექნიკური აუდიტი, ტოკენის შეფასება და საინვესტიციო რჩევა მომსახურებაში არ შედის.','Technical smart-contract audits, token valuation and investment advice are excluded.')},
 {id:'ai',slug:'ai',code:'04 / AI',name:pair('ხელოვნური ინტელექტი','AI & emerging technologies'),summary:pair('ხელოვნური ინტელექტის პროდუქტების შეფასება და კომპანიაში მისი გამოყენების წესები.','Legal review of AI products and practical governance for workplace AI.'),audience:pair('ხელოვნური ინტელექტის პროდუქტების შემქმნელები და კომპანიები, რომლებიც ასეთ ხელსაწყოებს იყენებენ.','AI product builders and businesses using AI tools.'),scope:pair(['მონაცემების, მოთხოვნებისა და გენერირებული შედეგების გამოყენება','ადამიანის ზედამხედველობა და ავტომატიზებული გადაწყვეტილებები','დაშვებული ხელსაწყოები და კონფიდენციალური ინფორმაციის დაცვა','მომწოდებლების პირობები და ინტელექტუალური საკუთრება','ევროკავშირის ხელოვნური ინტელექტის აქტის შესაძლო გავრცელების შეფასება'],['Data, prompts and output use','Human oversight and automated decisions','Approved tools and confidentiality','Provider terms and intellectual property','Assessment of potential EU AI Act applicability']),outputs:pair(['პროდუქტის ან გამოყენების შემთხვევის შეფასება','ხელოვნური ინტელექტის გამოყენების შიდა წესები','მომწოდებლის შეფასება და დანერგვის გეგმა'],['Product or use-case assessment','Internal AI use policy','Provider review and implementation plan']),questions:pair(['რას აკეთებს სისტემა და ვისზე ახდენს გავლენას მისი შედეგი?','რომელ მოდელებსა და მონაცემებს იყენებთ?','ვინ ამოწმებს შედეგს და როგორ წყდება შეცდომები?'],['What does the system do and who is affected?','Which models and data do you use?','Who checks outputs and handles errors?']),exclude:pair('მოდელის ტექნიკური უსაფრთხოების ტესტირება და შედეგების სიზუსტის სერტიფიცირება ცალკე სპეციალისტს მოითხოვს.','Technical model safety testing and output accuracy certification require separate specialists.')},
 {id:'data-protection',slug:'data-protection',code:'05 / PRIVACY',name:pair('მონაცემთა დაცვა','Data protection & privacy'),summary:pair('მონაცემთა დამუშავების პროცესების, დოკუმენტებისა და პასუხისმგებლობების მოწესრიგება.','Align data processes, documentation and responsibilities.'),audience:pair('კომპანიები, რომლებიც ამუშავებენ მომხმარებლების, თანამშრომლების ან პარტნიორების მონაცემებს.','Businesses processing customer, employee or partner data.'),scope:pair(['მონაცემთა ნაკადები, მიზნები და სამართლებრივი საფუძვლები','კონფიდენციალურობის შეტყობინებები და თანხმობის მართვა','მონაცემთა დამუშავების შეთანხმებები და საერთაშორისო გადაცემა','ზეგავლენის შეფასება, შენახვის ვადები და წვდომები','მონაცემთა სუბიექტის მოთხოვნები და ინციდენტებზე რეაგირება'],['Data flows, purposes and legal bases','Privacy notices and consent management','Processing agreements and international transfers','Impact assessments, retention and access','Data subject requests and incident response']),outputs:pair(['დამუშავების პროცესების რუკა','ხარვეზების შეფასება და დოკუმენტების პაკეტი','დანერგვისა და პერიოდული გადამოწმების გეგმა'],['Processing map','Gap assessment and document pack','Implementation and review plan']),questions:pair(['ვის მონაცემებს, რა მიზნით და საიდან იღებთ?','სად ინახება ინფორმაცია და ვის აქვს წვდომა?','როგორ პასუხობთ მოთხოვნებსა და ინციდენტებს?'],['Whose data do you collect, why and from where?','Where is it stored and who has access?','How do you handle requests and incidents?']),exclude:pair('უცხოური სამართლის შესახებ ფორმალური დასკვნის საჭიროებისას შესაბამის იურისდიქციაში მოქმედ იურისტს ვრთავთ.','Formal foreign-law opinions are coordinated with counsel in the relevant jurisdiction.')},
 {id:'contracts',slug:'contracts',code:'06 / CONTRACTS',name:pair('ტექნოლოგიური ხელშეკრულებები','Technology contracts'),summary:pair('კომერციული პირობები, რომლებიც ასახავს პროდუქტის, მონაცემებისა და მომსახურების რეალურ რისკებს.','Commercial terms grounded in the actual product, data and service risks.'),audience:pair('ტექნოლოგიების მყიდველი და მიმწოდებელი კომპანიები, SaaS და პროგრამული უზრუნველყოფის გუნდები.','Technology buyers and vendors, SaaS and software teams.'),scope:pair(['SaaS, ღრუბლოვანი სერვისები და ლიცენზირება','პროგრამული უზრუნველყოფის შექმნა, დანერგვა და API','მომსახურების დონე, მიღება-ჩაბარება და შეწყვეტა','მონაცემთა და ინტელექტუალური საკუთრების უფლებები','პასუხისმგებლობა, უსაფრთხოება და მოლაპარაკება'],['SaaS, cloud and licensing','Development, implementation and APIs','Service levels, acceptance and exit','Data and intellectual property rights','Liability, security and negotiation']),outputs:pair(['რისკების მოკლე შეფასება','შესწორებული ან მომზადებული ხელშეკრულება','მოლაპარაკების პრიორიტეტები'],['Concise risk assessment','Redlined or drafted agreement','Negotiation priorities']),questions:pair(['მყიდველი ხართ თუ მიმწოდებელი და რას ეხება შეთანხმება?','რა ღირებულება, ვადა და ძირითადი რისკებია?','რომელი პირობებია უკვე შეთანხმებული?'],['Are you the buyer or supplier and what is the agreement for?','What are the value, timeline and principal risks?','Which terms have already been agreed?']),exclude:pair('სასამართლო წარმოება, საგადასახადო დასკვნა და ტექნიკური სპეციფიკაციის აუდიტი ცალკე თანხმდება.','Litigation, tax opinions and technical specification audits are scoped separately.')},
 {id:'commerce',slug:'ecommerce',code:'07 / PLATFORMS',name:pair('ელექტრონული კომერცია და პლატფორმები','Digital commerce & platforms'),summary:pair('მომხმარებლისთვის გასაგები და ბიზნესმოდელზე მორგებული ციფრული მომსახურება.','Clear customer journeys and terms tailored to your business model.'),audience:pair('ონლაინმაღაზიები, მარკეტპლეისები, გამოწერის სერვისები და ციფრული პლატფორმები.','Online shops, marketplaces, subscription services and digital platforms.'),scope:pair(['სარგებლობისა და გამყიდველის პირობები','ფასის, გადახდისა და გამოწერის შესახებ ინფორმაცია','გაუქმების, დაბრუნებისა და საჩივრის პროცესები','რეკლამა, აქციები და პარტნიორული მარკეტინგი','მომხმარებლის კონტენტი და პლატფორმის პასუხისმგებლობა'],['User and seller terms','Pricing, payment and subscription disclosures','Cancellation, refund and complaint processes','Advertising, promotions and affiliate marketing','User content and platform responsibilities']),outputs:pair(['მომხმარებლის გზის შეფასება','პირობებისა და შეტყობინებების შესწორებები','პროდუქტის გუნდის სამოქმედო სია'],['Customer journey review','Revised terms and disclosures','Product team action list']),questions:pair(['რას ყიდით, ვის და რომელ ქვეყანაში?','როგორ მუშაობს გადახდა, გამოწერა და თანხის დაბრუნება?','ვის ეკუთვნის შეთავაზება და მომხმარებლის კონტენტი?'],['What do you sell, to whom and where?','How do payment, renewal and refunds work?','Who provides the offer and user content?']),exclude:pair('მარკეტინგული კამპანიის შესრულება და ტექნიკური დანერგვა მომსახურებაში არ შედის.','Campaign execution and technical implementation are excluded.')},
 {id:'cyber',slug:'cyber-digital-risk',code:'08 / DIGITAL RISK',name:pair('კიბერუსაფრთხოების სამართლებრივი საკითხები','Cybersecurity legal & governance'),summary:pair('ინციდენტებზე რეაგირება, მომწოდებლების ვალდებულებები და ციფრული რისკების მართვა.','Incident response, supplier obligations and digital risk governance.'),audience:pair('კომპანიების იურიდიული, უსაფრთხოების, შესაბამისობისა და შესყიდვების გუნდები.','Legal, security, compliance and procurement teams.'),scope:pair(['უსაფრთხოების სამართლებრივი და სახელშეკრულებო მოთხოვნები','ინციდენტზე რეაგირების სამართლებრივი გეგმა','შეტყობინების ვალდებულებების შეფასება','მომწოდებლების პასუხისმგებლობა და მმართველობა','მტკიცებულებებისა და გადაწყვეტილებების დოკუმენტირება'],['Legal and contractual security requirements','Legal incident response playbook','Notification obligation assessment','Supplier responsibility and governance','Evidence and decision records']),outputs:pair(['ვალდებულებების რუკა','რეაგირების გეგმა და პასუხისმგებელი პირები','სახელშეკრულებო დებულებები'],['Obligations map','Response plan and owners','Contract clauses']),questions:pair(['რა სისტემებსა და მონაცემებს ეხება საკითხი?','ინციდენტი უკვე მოხდა თუ პრევენციულად მუშაობთ?','რა ხელშეკრულებები და შიდა პროცედურები გაქვთ?'],['Which systems and data are involved?','Has an incident occurred or is this preventive work?','What contracts and procedures are in place?']),exclude:pair('შეღწევადობის ტესტირება, უსაფრთხოების მონიტორინგი და ტექნიკური ექსპერტიზა ჩვენი მომსახურება არ არის; საჭიროებისას პარტნიორს ვრთავთ.','Penetration testing, security monitoring and technical forensics require a specialist partner.')},
 {id:'georgia',slug:'georgia-market-entry',code:'09 / CROSS-BORDER',name:pair('ბაზარზე შესვლა','Market entry & regulatory strategy'),summary:pair('ციფრული ბიზნესის საქართველოში დაწყება და საერთაშორისო გაფართოების დაგეგმვა.','Launch digital business in Georgia and plan international expansion.'),audience:pair('საქართველოში შემომსვლელი საერთაშორისო კომპანიები და უცხო ბაზარზე გამსვლელი ქართული ტექნოლოგიური ბიზნესი.','International businesses entering Georgia and Georgian technology businesses expanding abroad.'),scope:pair(['ბიზნესმოდელი, ადგილობრივი კომპანია და საქმიანობის მოთხოვნები','რეგისტრაციისა და ავტორიზაციის საკითხები','პროდუქტის, პირობებისა და მონაცემთა პროცესების მორგება','ადგილობრივი პარტნიორები და ხელშეკრულებები','უცხოურ იურისტებთან კოორდინაცია'],['Business model, local entity and operating requirements','Registration and authorisation issues','Product, terms and data-process adaptation','Local partners and contracts','Coordination with foreign counsel']),outputs:pair(['ბაზარზე შესვლის სამართლებრივი გეგმა','მოთხოვნებისა და დამოკიდებულებების რუკა','გაშვებამდე შესასრულებელი სამუშაოების სია'],['Legal market-entry plan','Requirements and dependencies map','Pre-launch work plan']),questions:pair(['რომელი ქვეყნიდან და რომელ ბაზარზე გადიხართ?','რა პროდუქტი, კლიენტები და ადგილობრივი პარტნიორები გყავთ?','რა ვადაში გეგმავთ საქმიანობის დაწყებას?'],['From which country and into which market are you expanding?','What product, customers and local partners do you have?','When do you plan to launch?']),exclude:pair('საგადასახადო, საიმიგრაციო და უცხოური სამართლის სპეციალიზებული საკითხები ცალკე სპეციალისტებთან თანხმდება.','Specialist tax, immigration and foreign-law matters are agreed with relevant advisers.')}
];
export const solutions=[
 ['product-launch','product','ციფრული პროდუქტის გაშვებამდე შეფასება','Digital Product Launch Review','რა უნდა მოვაწესრიგოთ პროდუქტის გაშვებამდე?','What should we resolve before launch?'],
 ['fintech-assessment','fintech','ფინტექპროდუქტის რეგულირების შეფასება','FinTech Regulatory Assessment','რა მოთხოვნები ვრცელდება ჩვენს ბიზნესმოდელზე?','Which requirements apply to our business model?'],
 ['vasp-readiness','crypto','VASP-ის საქმიანობისთვის მომზადება','VASP Readiness','რა გვჭირდება ვირტუალური აქტივის სერვისის დასაწყებად?','What do we need to start a virtual asset service?'],
 ['ai-governance','ai','ხელოვნური ინტელექტის გამოყენების წესები','AI Governance Starter','როგორ გამოიყენოს გუნდმა ხელოვნური ინტელექტი პასუხისმგებლობით?','How should our team use AI responsibly?'],
 ['ai-product','ai','ხელოვნური ინტელექტის პროდუქტის შეფასება','AI Product Legal Review','რა სამართლებრივი საკითხები აქვს ჩვენს სისტემას?','Which legal issues does our AI system raise?'],
 ['privacy-review','data-protection','მონაცემთა დაცვის მდგომარეობის შეფასება','Privacy Compliance Review','რამდენად გამართულია ჩვენი მონაცემთა დამუშავების პროცესი?','How well are our data processes organised?'],
 ['contract-review','contracts','ტექნოლოგიური ხელშეკრულების შემოწმება','Technology Contract Review','რას ვაწერთ ხელს და რა უნდა შეიცვალოს?','What are we signing and what should change?'],
 ['enter-georgia','georgia','ციფრული ბიზნესის დაწყება საქართველოში','Enter Georgia','როგორ მოვარგოთ ჩვენი ბიზნესი ქართულ ბაზარს?','How do we adapt our business for Georgia?'],
 ['external-counsel','ongoing','თქვენი გუნდის გარე იურისტი','External Digital Counsel','გვჭირდება იურისტი მიმდინარე ციფრული და ტექნოლოგიური საკითხებისთვის.','We need ongoing digital and technology legal support.']
].map(([id,practice,ka,en,qka,qen])=>({id,practice,name:pair(ka,en),question:pair(qka,qen)}));
export const stages=pair(['გაცნობა','მოთხოვნების რუკა','შეფასება','გადაწყვეტა','დანერგვა','გაშვების შემოწმება','მიმდინარე მხარდაჭერა'],['Understand','Map','Assess','Design','Implement','Launch review','Maintain']);
const ongoing={id:'ongoing',name:pair('გარე იურიდიული მხარდაჭერა','External Digital Counsel'),scope:pair(['სამუშაოს ყოველთვიური მოცულობა და პრიორიტეტები','ხელშეკრულებებისა და ტექნოლოგიური საკითხების განხილვა','პროდუქტი, მონაცემები, ხელოვნური ინტელექტი და მომწოდებლები','რეგულირების ცვლილებების შეთანხმებული პერიოდული შეფასება'],['Monthly capacity and priorities','Contract and technology matters','Product, data, AI and vendors','Agreed periodic regulatory change review']),questions:pair(['რა სახის საკითხები და რა სიხშირით გიგროვდებათ?','ვინ არის საკონტაქტო პირი და როგორ თანხმდება პრიორიტეტები?','რა სამუშაო შედის ყოველთვიურ მოცულობაში და რა საჭიროებს ცალკე შეთანხმებას?'],['Which matters arise and how often?','Who is the contact and how are priorities agreed?','What is included monthly and what needs separate scoping?']),outputs:pair(['მიმდინარე საკითხების შეთანხმებული სია','დოკუმენტები და პრაქტიკული რჩევები','ყოველთვიური მიმოხილვა და შემდეგი პერიოდის გეგმა'],['Agreed live matter list','Documents and practical advice','Monthly review and next-period plan']),exclude:pair('სასამართლო წარმოება, ტექნიკური აუდიტი, უცხოური სამართლის ფორმალური დასკვნა და შეთანხმებულ მოცულობაზე მეტი სამუშაო ცალკე თანხმდება.','Litigation, technical audits, formal foreign-law opinions and work beyond the agreed capacity are scoped separately.')};
export const getPractice=id=>id==='ongoing'?ongoing:practices.find(p=>p.id===id)||practices[0];
export function scopeAreas({product='product',features=[],market='georgia'}={}){
 const ids=new Set(['product','contracts']);
 if(['fintech','crypto','ai','commerce'].includes(product))ids.add(product);
 if(product==='saas')ids.add('data-protection');
 if(features.includes('data'))ids.add('data-protection');
 if(features.includes('payments'))ids.add('fintech');
 if(features.includes('ai'))ids.add('ai');
 if(features.includes('consumer'))ids.add('commerce');
 if(features.includes('critical'))ids.add('cyber');
 if(market!=='georgia')ids.add('georgia');
 return practices.filter(p=>ids.has(p.id));
}
export function deliveryBlueprint(id,lang='ka'){
 const solution=solutions.find(s=>s.id===id);const p=getPractice(solution?.practice||id);
 if(id==='ai-governance')return {practice:p,solution,questions:pair(['რომელ ხელსაწყოებს იყენებს გუნდი და რა სამუშაოსთვის?','ხვდება თუ არა ხელსაწყოებში კონფიდენციალური ან პერსონალური ინფორმაცია?','ვინ ამტკიცებს ახალ ხელსაწყოს და ვინ ამოწმებს შედეგს?'],['Which tools are used and for which tasks?','Is confidential or personal information entered?','Who approves tools and reviews outputs?'])[lang],checks:pair(['დაშვებული ხელსაწყოების სია და აკრძალული გამოყენება','მონაცემთა დაცვისა და კონფიდენციალურობის წესები','მომწოდებლის პირობები და შესყიდვის პროცესი','ადამიანის ზედამხედველობა და ინციდენტის შეტყობინება','პასუხისმგებელი პირები და თანამშრომელთა ინსტრუქტაჟი'],['Approved tools and prohibited uses','Data and confidentiality rules','Provider terms and procurement process','Human oversight and incident escalation','Governance owners and staff briefing'])[lang],outputs:pair(['ხელოვნური ინტელექტის გამოყენების პოლიტიკა','ხელსაწყოს დამტკიცების კითხვარი','დანერგვისა და გადამოწმების გეგმა'],['AI use policy','Tool approval questionnaire','Implementation and review plan'])[lang],exclusion:p.exclude[lang]};
 return {practice:p,solution,questions:p.questions[lang],checks:p.scope[lang],outputs:p.outputs[lang],exclusion:p.exclude[lang]};
}
