import {scopeAreas} from './catalogue.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang=document.documentElement.lang==='en'?'en':'ka',product='product',last=null;
const say=(ka,en)=>lang==='en'?en:ka;
function preview(){const box=$('[data-scope-preview]');if(!box)return;box.innerHTML=scopeAreas({product}).map(p=>`<span>${esc(p.name[lang])}</span>`).join('');$('[data-scope-link]').href='/scope/?product='+product;}
document.querySelectorAll('[data-product]').forEach(b=>b.addEventListener('click',()=>{product=b.dataset.product;document.querySelectorAll('[data-product]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));preview();}));
preview();
function renderResult(){if(!last)return;const box=$('#scope-results'),areas=scopeAreas(last);box.innerHTML=`<div class="deliverable-card"><p class="eyebrow">YOUR PRODUCT / LEGAL MAP</p><h2>${say('შესაფასებელი მიმართულებები','Areas to review')}</h2>${areas.map(p=>`<div class="scope-result-card"><h3><a href="/services/${p.slug}/">${esc(p.name[lang])} ↗</a></h3><p>${esc(p.questions[lang][0])}</p></div>`).join('')}<p class="scope-disclaimer">${say('ეს არის თქვენი პასუხების მიხედვით შედგენილი საწყისი სია და არა სამართლებრივი დასკვნა ან გაშვების ნებართვა. მოთხოვნების გავრცელება, მოქმედი წესები და სხვა შესაძლო საკითხები იურისტმა უნდა შეაფასოს.','This is an initial list based on your answers, not legal advice or permission to launch. A lawyer needs to assess applicability, current rules and any further issues.')}</p><a class="button button-primary" id="scope-intake" href="/client/?service=${last.product==='saas'?'product':last.product}">${say('იურისტის შეფასების მოთხოვნა','Request a legal assessment')} ↗</a><p class="small">${say('გაგრძელებისას ამ პასუხებს მიმართვის შესავსებად თქვენს ბრაუზერში დროებით შევინახავთ.','When you continue, these answers are temporarily stored in your browser to prefill your enquiry.')}</p></div>`;$('#scope-intake').onclick=()=>{try{sessionStorage.setItem('dlg-scope',JSON.stringify(last));}catch{}};}
const form=$('#scope-form');if(form){const value=new URLSearchParams(location.search).get('product');if([...form.elements.product.options].some(o=>o.value===value))form.elements.product.value=value;form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);last={product:d.get('product'),features:d.getAll('features'),market:d.get('market')};renderResult();$('#scope-results').setAttribute('tabindex','-1');$('#scope-results').focus();};}
document.addEventListener('site:language',e=>{lang=e.detail.language;preview();renderResult();});
