import {practices,solutions,stages,getPractice} from './catalogue.mjs';
import {createDeliveryPack,feeEstimate} from './delivery-templates.mjs';
const URL='https://luygurjqpfgqnejtoihh.supabase.co',KEY='sb_publishable_vAjSddEW_E6gDxQE2E5saQ_opTxJzdD';
const admin=location.pathname.startsWith('/admin/'),root=document.querySelector('#workspace');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let language='ka';try{language=localStorage.getItem('dlg-language')==='en'?'en':'ka';}catch{}
const say=(ka,en)=>language==='en'?en:ka;
let sb,session,requests=[],selected,items=[],documents=[],events=[],files=[],approvals=[],detailTab='overview',loadVersion=0,activeUid=null;
const query=new URLSearchParams(location.search);let intent=Object.fromEntries(query);
try{if(query.size)sessionStorage.setItem('dlg-intent',JSON.stringify(intent));else intent=JSON.parse(sessionStorage.getItem('dlg-intent')||'{}');}catch{}
const statusNames={submitted:['გაგზავნილია','Submitted'],reviewing:['განხილვის პროცესში','In review'],in_progress:['მუშაობის პროცესში','In progress'],waiting_for_client:['თქვენი პასუხია საჭირო','Your input needed'],completed:['დასრულებულია','Completed'],closed:['დახურულია','Closed']};
const stateNames={open:['შესასრულებელი','Open'],in_progress:['მიმდინარეობს','In progress'],blocked:['შეჩერებულია','Blocked'],done:['შესრულებულია','Done']};
const kindNames={task:['დავალება','Task'],risk:['რისკი','Risk'],question:['კითხვა','Question'],check:['შესამოწმებელი','Checklist'],monitoring:['პერიოდული გადამოწმება','Periodic review']};
const docNames={proposal:['შეთავაზება','Proposal'],engagement:['მომსახურების პირობები','Engagement'],analysis:['შეფასება','Analysis'],deliverable:['საბოლოო შედეგი','Deliverable']};
const label=(map,key)=>map[key]?say(...map[key]):key;
function readableIntake(key,value){if(key==='answers'&&Array.isArray(value))return value.map(x=>x.question+'\n'+x.answer).join('\n\n');if(key==='scope'&&value&&typeof value==='object'){const features={data:say('მონაცემები','Data'),payments:say('გადახდები','Payments'),ai:say('ხელოვნური ინტელექტი','AI'),consumer:say('ონლაინგაყიდვა','Online sales'),critical:say('უსაფრთხოება','Security')};return [getPractice(value.product).name[language],...(value.features||[]).map(x=>features[x]||x),value.market].filter(Boolean).join(' · ');}return typeof value==='object'?say('დამატებითი ინფორმაცია მიღებულია.','Additional information received.'):value;}
const date=v=>v?new Intl.DateTimeFormat(language==='en'?'en-GB':'ka-GE',{dateStyle:'medium'}).format(new Date(v)):say('შესათანხმებელია','To be agreed');
const empty=text=>`<div class="w-empty">${esc(text)}</div>`;
const button=(action,text,cls='')=>`<button type="button" class="w-button ${cls}" data-action="${action}">${text}</button>`;
function notice(message,error=false){const el=$('#w-notice');el.textContent=message;el.className='w-notice'+(error?' error':'');el.hidden=!message;}
function fail(){notice(say('მოქმედება ვერ შესრულდა. ცვლილება არ დადასტურებულა. სცადეთ ხელახლა.','The action could not be confirmed. Please try again.'),true);}
async function checked(promise){const r=await promise;if(r.error)throw r.error;return r.data;}
async function run(button,fn){if(button)button.disabled=true;try{await fn();}catch{fail();}finally{if(button?.isConnected)button.disabled=false;}}
function download(name,body,type='text/plain;charset=utf-8'){const blob=body instanceof Blob?body:new Blob([body],{type});const url=URLCreate(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>window.URL.revokeObjectURL(url),10000);}
const URLCreate=blob=>window.URL.createObjectURL(blob);
function frame(){document.documentElement.lang=language;document.title=say(admin?'მიმართვების მართვა | DLG':'კლიენტის სივრცე | DLG',admin?'Request management | DLG':'Client workspace | DLG');root.innerHTML=`<header class="w-header"><a href="/" class="w-brand"><b>DLG</b><span>DIGITAL LAW<br><small>GEORGIA</small></span></a><div class="w-header-right"><a href="/">${say('საიტზე დაბრუნება','Back to website')}</a>${button('lang',language==='ka'?'EN':'KA','quiet')}<span id="w-account"></span></div></header><main class="w-main"><div id="w-notice" class="w-notice" role="status" hidden></div><div id="w-content">${empty(say('სივრცე იტვირთება…','Loading workspace…'))}</div></main><dialog id="w-dialog" class="w-dialog"></dialog>`;root.addEventListener('click',routeClick);}
function login(denied=false){$('#w-account').innerHTML=session?button('logout',say('გასვლა','Sign out'),'quiet'):'';$('#w-content').innerHTML=`<section class="w-login"><div><p class="w-overline">DIGITAL LAW GEORGIA / ${admin?'DELIVERY DESK':'CLIENT WORKSPACE'}</p><h1>${say(admin?'თქვენი სამუშაო პროცესი ერთ სივრცეში.':'თქვენი პროდუქტი. თქვენი საკითხები. ერთი სამუშაო სივრცე.',admin?'Your delivery work in one place.':'Your product. Your matters. One workspace.')}</h1><p>${say('მიმართვიდან შედეგის მიღებამდე — შეთანხმებული სამუშაო, დავალებები, დოკუმენტები და მიმოწერა.','From enquiry to delivery: agreed scope, actions, documents and communication.')}</p><div class="w-login-path"><span>01 ${say('მიმართვა','Enquiry')}</span><span>02 ${say('შეთანხმება','Agreement')}</span><span>03 ${say('შესრულება','Delivery')}</span></div></div><div class="w-login-card"><span class="w-orbit" aria-hidden="true">✳</span><h2>${say(denied?'ამ ანგარიშს ადმინისტრატორის წვდომა არ აქვს.':'შედით თქვენს სივრცეში.',denied?'This account does not have administrator access.':'Sign in to your workspace.')}</h2><p>${say('Google-ის ანგარიში გამოიყენება თქვენი იდენტიფიკაციისთვის. მიმართვები და ფაილები ხელმისაწვდომია შესაბამისი კლიენტისა და DLG-ის უფლებამოსილი ადმინისტრატორებისთვის.','Google identifies your account. Matters and files are accessible to the relevant client and authorised DLG administrators.')}</p>${denied?'':button('google',say('Google-ით გაგრძელება →','Continue with Google →'),'primary')}<a href="mailto:digitallawgeorgia@gmail.com">${say('ან მოგვწერეთ ელფოსტით','Or contact us by email')}</a><a class="w-small" href="/privacy/">${say('კონფიდენციალურობა','Privacy')}</a></div></section>`;}
async function showSession(){if(!session){activeUid=null;requests=[];selected=null;login();return;}if(admin){const a=await checked(sb.from('dlg_admin_users').select('email'));if(!a.length){login(true);return;}}activeUid=session.user.id;await refresh();if(!admin&&(intent.service||intent.solution||intent.new||intent.consultation)){openIntake();intent={};try{sessionStorage.removeItem('dlg-intent');}catch{}}}
async function refresh(){let q=sb.from('dlg_client_requests').select('*').order('created_at',{ascending:false});if(!admin)q=q.eq('user_id',session.user.id);requests=await checked(q);selected=requests.find(r=>r.id===selected?.id)||requests[0];dashboard();if(selected)await detail();}
function dashboard(){const open=requests.filter(r=>!['closed','completed'].includes(r.status)).length;$('#w-account').innerHTML=button('logout',say('გასვლა','Sign out'),'quiet');$('#w-content').innerHTML=`<div class="w-heading"><div><p class="w-overline">DLG / ${admin?'DELIVERY DESK':'YOUR WORKSPACE'}</p><h1>${say(admin?'კლიენტების საკითხები':'მოგესალმებით',admin?'Client matters':'Welcome')}</h1><p class="w-small">${esc(session.user.email)}</p></div>${admin?button('export',say('მონაცემების ჩამოტვირთვა','Export matters'),'quiet'):button('new',say('+ ახალი მიმართვა','+ New enquiry'),'primary')}</div><div class="w-stats"><div><b>${requests.length}</b><span>${say('ყველა მიმართვა','All matters')}</span></div><div><b>${open}</b><span>${say('მიმდინარე','Open')}</span></div><div><b>${requests.filter(r=>r.status==='completed').length}</b><span>${say('დასრულებული','Completed')}</span></div></div>${admin?`<details class="w-operations"><summary>${say('პერიოდული გადამოწმება და ვადები','Periodic reviews and due dates')}</summary><p class="w-small">${say('აქ ჩანს თქვენ მიერ დაგეგმილი სამუშაო. სამართლებრივი წყაროების ავტომატური მონიტორინგი ჩართული არ არის.','This shows work you have scheduled. Automated monitoring of legal sources is not enabled.')}</p>${button('due',say('ვადების ნახვა','Load due work'),'quiet')}<div id="w-due"></div></details>`:''}<div class="w-grid"><aside class="w-sidebar"><label class="w-small" for="w-search">${say('მიმართვის ძიება','Search matters')}</label><input id="w-search" type="search" placeholder="${say('სათაური ან კომპანია','Title or company')}"><div id="w-list"></div></aside><section class="w-detail" id="w-detail">${empty(say('მიმართვა ჯერ არ გაქვთ. დაიწყეთ მოკლე აღწერით.','No matters yet. Start with a short brief.'))}</section></div>`;$('#w-search').oninput=renderList;renderList();}
function renderList(){const term=($('#w-search')?.value||'').toLowerCase();$('#w-list').innerHTML=requests.filter(r=>[r.title,r.company_name,r.client_email].join(' ').toLowerCase().includes(term)).map(r=>`<button type="button" class="w-matter ${r.id===selected?.id?'active':''}" data-select="${r.id}"><span class="w-badge">${esc(label(statusNames,r.status))}</span><strong>${esc(r.title)}</strong><small>${esc(r.company_name||r.service_label)} · ${date(r.created_at)}</small></button>`).join('')||empty(say('მიმართვა ვერ მოიძებნა.','No matching matters.'));}
async function detail(){const seq=++loadVersion,id=selected.id;$('#w-detail').innerHTML=empty(say('ინფორმაცია იტვირთება…','Loading matter…'));const [it,ds,ev,fl,ap]=await Promise.all([checked(sb.from('dlg_delivery_items').select('*').eq('request_id',id).order('created_at')),checked(sb.from('dlg_documents').select('*').eq('request_id',id).order('created_at')),checked(sb.from('dlg_client_request_events').select('*').eq('request_id',id).order('created_at')),checked(sb.storage.from('dlg-matter-files').list(id,{limit:100,sortBy:{column:'created_at',order:'desc'}})),checked(sb.from('dlg_document_approvals').select('*'))]);if(seq!==loadVersion||id!==selected?.id)return;items=it;documents=ds;events=ev;files=fl;approvals=ap;renderDetail();}
function renderDetail(){const r=selected;$('#w-detail').innerHTML=`<div class="w-detail-head"><div><span class="w-badge">${esc(label(statusNames,r.status))}</span><h2>${esc(r.title)}</h2><p class="w-small">${esc(r.company_name||'')} · ${date(r.created_at)} · ${esc(r.id.slice(0,8))}</p></div>${button('refresh','↻','quiet')}</div><div class="w-stage">${stages[language].map((s,i)=>`<span class="${i===(r.delivery_stage||0)?'current':''}"><b>${i+1}</b>${s}</span>`).join('')}</div><nav class="w-tabs" aria-label="${say('მიმართვის განყოფილებები','Matter sections')}">${[['overview','მიმოხილვა','Overview'],['work','სამუშაო','Work'],['documents','დოკუმენტები','Documents'],['files','ფაილები','Files'],['messages','მიმოწერა','Messages']].map(([id,ka,en])=>`<button type="button" data-tab="${id}" aria-pressed="${detailTab===id}">${say(ka,en)}</button>`).join('')}</nav><div id="w-pane"></div>`;renderPane();}
function renderPane(){const p=$('#w-pane'),r=selected;
 if(detailTab==='overview'){p.innerHTML=`<p class="w-pre">${esc(r.description)}</p><dl class="w-facts">${Object.entries(r.intake||{}).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>`<div><dt>${esc(({market:say('ბაზარი','Market'),product_stage:say('პროდუქტის ეტაპი','Product stage'),website:say('ვებსაიტი','Website'),target_date:say('სასურველი ვადა','Target date'),consultation:say('კონსულტაციის სასურველი დრო','Preferred consultation time'),answers:say('დამატებითი ინფორმაცია','Additional information'),scope:say('საწყისი კითხვარის პასუხები','Scope answers')})[k]||k)}</dt><dd>${esc(readableIntake(k,v))}</dd></div>`).join('')}</dl>${r.intake?.consultation?`<p class="w-small">${say('შეხვედრის დრო მოთხოვნილია და დადასტურებას საჭიროებს.','The requested meeting time needs confirmation.')}</p>`:''}${admin?`<div class="w-admin-tools"><h3>${say('სამუშაოს მართვა','Manage delivery')}</h3><form id="progress-form" class="w-form"><label>${say('სტატუსი','Status')}<select name="status">${Object.keys(statusNames).map(k=>`<option value="${k}" ${r.status===k?'selected':''}>${label(statusNames,k)}</option>`).join('')}</select></label><label>${say('ეტაპი','Stage')}<select name="stage">${stages[language].map((s,i)=>`<option value="${i}" ${i===(r.delivery_stage||0)?'selected':''}>${i+1}. ${s}</option>`).join('')}</select></label><button class="w-button primary">${say('შენახვა','Save')}</button></form>${items.length||documents.length?'':button('seed',say('მომსახურების სამუშაო პაკეტის შექმნა','Create service delivery pack'),'primary')}<p class="w-small">${say('პაკეტი ქმნის კითხვებს, შემოწმების სიას, დავალებებსა და ოთხ სამუშაო დოკუმენტს. იურისტის შევსება და გადამოწმება აუცილებელია.','Creates questions, a checklist, tasks and four draft documents. Lawyer completion and review are required.')}</p>${button('pricing',say('საფასურის გამოთვლა','Fee calculator'),'quiet')}${button('bundle',say('სამუშაოს ექსპორტი','Export delivery'),'quiet')}</div>`:''}`;if(admin)$('#progress-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const f=new FormData(e.target);await checked(sb.rpc('dlg_update_progress',{rid:r.id,new_status:f.get('status'),new_stage:Number(f.get('stage'))}));await refresh();notice(say('ეტაპი და სტატუსი შენახულია.','Stage and status saved.'));});};}
 if(detailTab==='work'){p.innerHTML=`<div class="w-pane-heading"><h3>${say('დავალებები, რისკები და კითხვები','Tasks, risks and questions')}</h3>${admin?button('add-item',say('+ დამატება','+ Add'),'primary'):''}</div>${items.length?items.map(x=>`<article class="w-work-card"><div class="w-work-meta"><span>${esc(label(kindNames,x.kind))}</span><span class="w-badge ${x.priority==='urgent'||x.priority==='high'?'amber':''}">${esc(label(stateNames,x.state))}</span>${admin?`<small>${x.shared?say('კლიენტთან გაზიარებული','Shared with client'):say('შიდა სამუშაო','Internal')}</small>`:''}</div><h4>${esc(x.title)}</h4>${x.requirement?`<p><strong>${say('მოთხოვნა / საფუძველი:','Requirement / basis:')}</strong> ${esc(x.requirement)}</p>`:''}${x.action?`<p class="w-pre">${esc(x.action)}</p>`:''}<div class="w-work-meta"><span>${esc(x.owner_label||say('პასუხისმგებელი შესათანხმებელია','Owner to be agreed'))}</span><span>${date(x.due_date)}</span>${x.source_url?`<a href="${esc(x.source_url)}" target="_blank" rel="noopener noreferrer">${say('წყარო ↗','Source ↗')}</a>`:''}</div>${admin?`<button class="w-button quiet" data-edit-item="${x.id}">${say('რედაქტირება','Edit')}</button>`:''}</article>`).join(''):empty(say('სამუშაო სია ჯერ არ დამატებულა. მას საკითხის გაცნობისა და მოცულობის შეთანხმების შემდეგ შევავსებთ.','The work list will be prepared after initial review and scope agreement.'))}`;}
 if(detailTab==='documents'){p.innerHTML=`<div class="w-pane-heading"><h3>${say('სამუშაო და საბოლოო დოკუმენტები','Working and final documents')}</h3>${admin?button('add-doc',say('+ დოკუმენტი','+ Document'),'primary'):''}</div>${documents.length?documents.map(d=>`<article class="w-doc"><div class="w-work-meta"><span>${esc(label(docNames,d.kind))} · v${d.version}</span><span class="w-badge">${d.published?say('გამოქვეყნებულია','Published'):say('სამუშაო პროექტი','Draft')}</span></div><h4>${esc(d.title)}</h4><details><summary>${say('ტექსტის ნახვა','Read document')}</summary><div class="w-document-text">${esc(d.body)}</div></details><div class="w-actions"><button class="w-button quiet" data-download-doc="${d.id}">${say('ჩამოტვირთვა','Download')}</button>${admin?`<button class="w-button quiet" data-edit-doc="${d.id}">${say('რედაქტირება','Edit')}</button><button class="w-button ${d.published?'quiet':'primary'}" data-publish-doc="${d.id}">${d.published?say('გაზიარების შეჩერება','Unpublish'):say('კლიენტთან გამოქვეყნება','Publish to client')}</button>`:d.kind!=='analysis'&&!approvals.some(a=>a.document_id===d.id&&a.version===d.version)?`<button class="w-button primary" data-approve-doc="${d.id}">${say('გაცნობა და თანხმობა','Review and approve')}</button>`:''}</div>${approvals.filter(a=>a.document_id===d.id).map(a=>`<p class="w-small">${say('თანხმობა აღრიცხულია','Approval recorded')}: v${a.version} · ${date(a.approved_at)}${a.version!==d.version?' · '+say('წინა ვერსია','previous version'):''}</p>`).join('')}</article>`).join(''):empty(say('დოკუმენტები ჯერ არ გამოქვეყნებულა.','No documents have been published yet.'))}`;}
 if(detailTab==='files'){p.innerHTML=`<h3>${say('გაზიარებული ფაილები','Shared files')}</h3><p class="w-small">${say('ფაილებს ხედავთ თქვენ და DLG-ის უფლებამოსილი ადმინისტრატორები. PDF, DOCX, TXT, PNG ან JPG — მაქსიმუმ 10 მბ თითო ფაილზე.','Files are visible to you and authorised DLG administrators. PDF, DOCX, TXT, PNG or JPG, up to 10 MB each.')}</p><form id="upload-form" class="w-form"><label>${say('ფაილის არჩევა','Choose a file')}<input required type="file" name="file" accept=".pdf,.docx,.txt,.png,.jpg,.jpeg"></label><button class="w-button primary">${say('ატვირთვა','Upload')}</button></form>${files.length?files.map(f=>`<div class="w-file"><span>${esc(f.name.replace(/^[a-f0-9-]{36}--/,''))}</span><button class="w-button quiet" data-download-file="${esc(f.name)}">${say('ჩამოტვირთვა','Download')}</button></div>`).join(''):empty(say('ფაილები ჯერ არ ატვირთულა.','No files uploaded yet.'))}`;$('#upload-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{await uploadFile(r.id,new FormData(e.target).get('file'));await detail();notice(say('ფაილი ატვირთულია.','File uploaded.'));});};}
 if(detailTab==='messages'){p.innerHTML=`<h3>${say('მიმოწერა და განახლებები','Messages and updates')}</h3><div class="w-timeline">${events.map(e=>`<article><small>${date(e.created_at)} · ${say(e.event_type==='client_message'?'კლიენტი':e.event_type==='admin_update'?'DLG':'განახლება',e.event_type==='client_message'?'Client':e.event_type==='admin_update'?'DLG':'Update')}</small><p class="w-pre">${esc(e.message)}</p></article>`).join('')}</div><form class="w-form" id="message-form"><label>${say('ახალი შეტყობინება','New message')}<textarea required minlength="1" maxlength="12000" name="message" rows="4"></textarea></label><p class="w-small">${say('შეტყობინება ხილული იქნება ორივე მხარისთვის.','The message will be visible to both parties.')}</p><button class="w-button primary">${say('გაგზავნა','Send')}</button></form>`;$('#message-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const message=new FormData(e.target).get('message').trim();if(!message)return;await checked(sb.from('dlg_client_request_events').insert({request_id:r.id,user_id:session.user.id,event_type:admin?'admin_update':'client_message',message}));await detail();notice(say('შეტყობინება გაიგზავნა.','Message sent.'));});};}
}
function modal(title,body,onSubmit){const d=$('#w-dialog');d.innerHTML=`<div class="w-dialog-head"><h2>${esc(title)}</h2><button type="button" class="w-button quiet" data-action="close" aria-label="${say('დახურვა','Close')}">×</button></div>${body}<p class="w-form-error" role="status"></p>`;d.showModal();const form=d.querySelector('form');if(form)form.onsubmit=e=>{e.preventDefault();const b=e.submitter;runModal(b,()=>onSubmit(Object.fromEntries(new FormData(form)),form,b));};}
async function runModal(b,fn){b.disabled=true;try{await fn();}catch{$('#w-dialog .w-form-error').textContent=say('შენახვა ვერ მოხერხდა. გადაამოწმეთ მონაცემები და სცადეთ ხელახლა.','Could not save. Check the values and try again.');}finally{if(b.isConnected)b.disabled=false;}}
const field=(name,title,value='',type='text',required=false)=>`<label>${esc(title)}<input type="${type}" name="${name}" value="${esc(value)}" ${required?'required':''} ${type==='text'?'maxlength="240"':''}></label>`;
const textarea=(name,title,value='',limit=12000)=>`<label>${esc(title)}<textarea name="${name}" maxlength="${limit}" rows="5">${esc(value)}</textarea></label>`;
const options=(name,map,value)=>`<label>${say(name==='kind'?'ტიპი':name==='state'?'სტატუსი':'პრიორიტეტი',name)}<select name="${name}">${Object.keys(map).map(k=>`<option value="${k}" ${value===k?'selected':''}>${esc(label(map,k))}</option>`).join('')}</select></label>`;
function openIntake(){const wanted=intent.service||query.get('service')||'product';const service=practices.some(p=>p.id===wanted)||wanted==='ongoing'?wanted:'product';const solution=intent.solution||query.get('solution')||'';let scope;try{scope=JSON.parse(sessionStorage.getItem('dlg-scope')||'null');}catch{}
 modal(say('მოგვიყევით თქვენი საკითხის შესახებ','Tell us about your matter'),`<form class="w-form"><label>${say('მომსახურება','Service')}<select name="service_slug">${practices.map(p=>`<option value="${p.id}" ${service===p.id?'selected':''}>${esc(p.name[language])}</option>`).join('')}<option value="ongoing" ${service==='ongoing'?'selected':''}>${say('გარე იურიდიული მხარდაჭერა','External digital counsel')}</option></select></label><label>${say('კონკრეტული შეთავაზება','Solution')}<select name="solution_slug"><option value="">${say('ჯერ არ ვიცი','Not sure yet')}</option>${solutions.map(s=>`<option value="${s.id}" ${s.id===solution?'selected':''}>${esc(s.name[language])}</option>`).join('')}</select></label>${field('title',say('საკითხის მოკლე სათაური','Short matter title'),'','text',true)}${field('company_name',say('კომპანია / პროექტი','Company / project'))}${textarea('description',say('რა გსურთ მოაგვაროთ ან რა შედეგი გჭირდებათ?','What do you need to resolve or achieve?'))}<div class="w-form-grid">${field('market',say('ქვეყნები / სამიზნე ბაზარი','Countries / target markets'),scope?.market||'საქართველო')}${field('product_stage',say('პროდუქტის ეტაპი','Product stage'))}${field('website',say('პროდუქტის ბმული (არასავალდებულო)','Product URL (optional)'),'','url')}${field('target_date',say('სასურველი ვადა','Target date'),'','date')}</div><div id="intake-questions"></div>${(intent.consultation||query.get('consultation'))?`${field('consultation',say('კონსულტაციის სასურველი დრო — თბილისის დროით','Preferred consultation time — Tbilisi time'),'','datetime-local')}<p class="w-small">${say('ეს დრო წინასწარ დადასტურებული არ არის. შეხვედრას მიმოწერაში შევათანხმებთ.','This is a request, not a confirmed booking. We will confirm the meeting in messages.')}</p>`:''}<label>${say('დოკუმენტი (არასავალდებულო, მაქს. 10 მბ)','Document (optional, max 10 MB)')}<input type="file" name="attachment" accept=".pdf,.docx,.txt,.png,.jpg,.jpeg"></label><p class="w-small">${say('მიმართვის გაგზავნა ფასიან შეკვეთას არ ნიშნავს. საფასურსა და მომსახურების პირობებს სამუშაოს დაწყებამდე ვათანხმებთ. ფაილს გამოიყენებენ საკითხის განმხილველი ადმინისტრატორები.','An enquiry is not a paid order. Fees and engagement terms are agreed before work begins. Uploaded files are available to the administrators reviewing your matter.')}</p><label class="w-checkbox"><input type="checkbox" required>${say('გავეცანი კონფიდენციალურობის ინფორმაციას.','I have read the privacy information.')} <a href="/privacy/" target="_blank">↗</a></label><button class="w-button primary">${say('მიმართვის გაგზავნა','Submit enquiry')}</button></form>`,async(v,f)=>{
 const title=v.title.trim(),description=v.description.trim();if(title.length<3||title.length>180||description.length<10)throw Error('Invalid brief');const file=new FormData(f).get('attachment');if(file?.size)validateFile(file);
 const p=practices.find(p=>p.id===v.service_slug),answers=[...f.querySelectorAll('[data-question]')].map(e=>({question:e.dataset.question,answer:e.value.trim()})).filter(x=>x.answer);
 const rid=await checked(sb.rpc('dlg_submit_request',{payload:{title,description,service_slug:v.service_slug,service_label:p?.name.ka||'გარე იურიდიული მხარდაჭერა',solution_slug:v.solution_slug||null,company_name:v.company_name,client_name:session.user.user_metadata?.full_name||'',preferred_language:language,intake:{market:v.market,product_stage:v.product_stage,website:v.website,target_date:v.target_date,consultation:v.consultation?`${v.consultation} (Asia/Tbilisi)`:'',answers,scope:scope||undefined}}}));
 let uploaded=true;if(file?.size){try{await uploadFile(rid,file);}catch{uploaded=false;}}$('#w-dialog').close();try{sessionStorage.removeItem('dlg-scope');}catch{}selected={id:rid};await refresh();notice(uploaded?say('მიმართვა მიღებულია. აქ ნახავთ პასუხსა და შემდეგ ნაბიჯებს.','Enquiry received. Updates and next steps will appear here.'):say('მიმართვა მიღებულია, მაგრამ ფაილი ვერ აიტვირთა. ხელახლა ატვირთეთ „ფაილების“ განყოფილებიდან.','Enquiry received, but the file upload failed. Retry from the Files section.'),!uploaded);
 });const f=$('#w-dialog form');f.elements.title.maxLength=180;f.elements.title.minLength=3;f.elements.description.required=true;f.elements.description.minLength=10;function questions(){const p=getPractice(f.elements.service_slug.value);$('#intake-questions').innerHTML=`<h3>${say('დასაწყისისთვის სასარგებლო დეტალები','Useful starting details')}</h3>${p.questions[language].map((q,i)=>`<label>${esc(q)}<textarea data-question="${esc(q)}" name="q${i}" rows="2" maxlength="2500"></textarea></label>`).join('')}`;}f.elements.service_slug.onchange=()=>{questions();if(f.elements.solution_slug.value&&solutions.find(s=>s.id===f.elements.solution_slug.value)?.practice!==f.elements.service_slug.value)f.elements.solution_slug.value='';};f.elements.solution_slug.onchange=()=>{const s=solutions.find(s=>s.id===f.elements.solution_slug.value);if(s){f.elements.service_slug.value=s.practice;questions();}};questions();}
function editItem(id){const x=items.find(i=>i.id===id)||{kind:'task',state:'open',priority:'normal',shared:false};modal(say('სამუშაო პუნქტი','Work item'),`<form class="w-form"><div class="w-form-grid">${options('kind',kindNames,x.kind)}${options('state',stateNames,x.state)}</div>${field('title',say('საკითხი / დავალება','Issue / task'),x.title,'text',true)}${textarea('requirement',say('მოთხოვნა და სამართლებრივი საფუძველი','Requirement and legal basis'),x.requirement)}${textarea('action',say('რეკომენდებული ცვლილება / პასუხი / შესრულების მტკიცებულება','Recommended change / answer / completion evidence'),x.action)}<div class="w-form-grid">${field('owner_label',say('პასუხისმგებელი','Owner'),x.owner_label)}${field('due_date',say('ვადა','Due date'),x.due_date,'date')}${options('priority',{low:['დაბალი','Low'],normal:['ჩვეულებრივი','Normal'],high:['მაღალი','High'],urgent:['გადაუდებელი','Urgent']},x.priority)}${field('review_days',say('პერიოდული გადამოწმება — დღეების რაოდენობა','Review interval — days'),x.review_days,'number')}</div>${field('source_url',say('ოფიციალური წყარო — HTTPS ბმული','Official source — HTTPS URL'),x.source_url,'url')}<label class="w-checkbox"><input name="shared" type="checkbox" ${x.shared?'checked':''}>${say('კლიენტისთვის ხილული','Visible to client')}</label><button class="w-button primary">${say('შენახვა','Save')}</button></form>`,async(v)=>{const row={...v,shared:v.shared==='on',due_date:v.due_date||null,review_days:v.review_days?Number(v.review_days):null,updated_at:new Date().toISOString()};if(row.source_url&&!row.source_url.startsWith('https://'))throw Error('HTTPS required');if(id)await checked(sb.from('dlg_delivery_items').update(row).eq('id',id).select().single());else await checked(sb.from('dlg_delivery_items').insert({...row,request_id:selected.id}).select().single());$('#w-dialog').close();await detail();notice(say('სამუშაო პუნქტი შენახულია.','Work item saved.'));});}
function editDoc(id){const d=documents.find(x=>x.id===id)||{kind:'analysis'};modal(say('დოკუმენტის რედაქტირება','Edit document'),`<form class="w-form">${options('kind',docNames,d.kind)}${field('title',say('სათაური','Title'),d.title,'text',true)}${textarea('body',say('ტექსტი','Document text'),d.body,80000)}<p class="w-small">${say('შინაარსის შეცვლისას შეიქმნება ახალი ვერსია და გაზიარება შეჩერდება. გამოქვეყნება ცალკე მოქმედებაა.','Editing content creates a new version and unpublishes it. Publication is a separate action.')}</p><button class="w-button primary">${say('სამუშაო პროექტის შენახვა','Save draft')}</button></form>`,async(v)=>{if(!v.body.trim())throw Error('Body required');if(id)await checked(sb.from('dlg_documents').update(v).eq('id',id).select().single());else await checked(sb.from('dlg_documents').insert({...v,request_id:selected.id}).select().single());$('#w-dialog').close();await detail();notice(say('სამუშაო პროექტი შენახულია.','Draft saved.'));});$('#w-dialog textarea').rows=17;}
function approveDoc(id){const d=documents.find(x=>x.id===id);modal(say('დოკუმენტის გაცნობა და თანხმობა','Review and approve'),`<form class="w-form"><h3>${esc(d.title)} · v${d.version}</h3><div class="w-document-text">${esc(d.body)}</div><p class="w-small">${say('თანხმობა ჩაიწერება თქვენს ანგარიშზე, ამ ვერსიის ტექსტითა და თარიღით. ეს არ არის კვალიფიციური ელექტრონული ხელმოწერა.','Approval is recorded against your account with this version, its text and the date. This is not a qualified electronic signature.')}</p><label class="w-checkbox"><input type="checkbox" required>${say('გავეცანი ამ ვერსიას და ვეთანხმები მის შინაარსს.','I have read this version and agree to its contents.')}</label><button class="w-button primary">${say('თანხმობის დადასტურება','Confirm approval')}</button></form>`,async()=>{await checked(sb.from('dlg_document_approvals').insert({document_id:id,user_id:session.user.id,version:d.version,body_snapshot:d.body}));$('#w-dialog').close();await detail();notice(say('თანხმობა აღრიცხულია.','Approval recorded.'));});}
function pricing(){modal(say('საფასურის სამუშაო გაანგარიშება','Working fee estimate'),`<form class="w-form"><p class="w-small">${say('შიდა გაანგარიშება. თანხები წინასწარ დადგენილი არ არის და კლიენტთან ავტომატურად არ იგზავნება. გადასახადები და დამატებითი ხარჯები შეთავაზებაში ცალკე განსაზღვრეთ.','Internal estimate. Rates are not preset and nothing is sent to the client automatically. Specify taxes and external costs in the proposal.')}</p>${field('hours',say('სავარაუდო საათები','Estimated hours'),'','number',true)}${field('rate',say('საათობრივი განაკვეთი','Hourly rate'),'','number',true)}${field('external',say('დამატებითი ხარჯები','External costs'),'0','number')}${field('contingency',say('სირთულის რეზერვი (%)','Complexity contingency (%)'),'0','number')}${field('currency',say('ვალუტა','Currency'),'GEL')}<button class="w-button primary">${say('გამოთვლა','Calculate')}</button><output id="fee-output" aria-live="polite"></output></form>`,async(v)=>{$('#fee-output').textContent=feeEstimate(v).toLocaleString(language==='en'?'en-GB':'ka-GE')+' '+v.currency;});$$('#w-dialog input[type=number]').forEach(e=>{e.min='0';e.step='0.01';});}
function validateFile(f){if(!f||!f.size||f.size>10485760||!['pdf','docx','txt','png','jpg','jpeg'].includes(f.name.split('.').pop().toLowerCase()))throw Error('Unsupported file');}
async function uploadFile(rid,f){validateFile(f);const name=crypto.randomUUID()+'--'+f.name.normalize('NFKC').replace(/[^\p{L}\p{N}._ -]/gu,'_').slice(-140);await checked(sb.storage.from('dlg-matter-files').upload(rid+'/'+name,f,{upsert:false,contentType:f.type||'application/octet-stream'}));}
async function dueWork(){const today=new Date().toISOString().slice(0,10);const due=await checked(sb.from('dlg_delivery_items').select('*').neq('state','done').lte('due_date',today).order('due_date'));$('#w-due').innerHTML=due.map(x=>`<button class="w-matter" data-select="${x.request_id}"><strong>${esc(x.title)}</strong><small>${date(x.due_date)} · ${esc(x.owner_label)}</small></button>`).join('')||empty(say('ვადამოსული სამუშაო არ არის.','No work is due.'));}
async function routeClick(e){const b=e.target.closest('button');if(!b)return;const action=b.dataset.action;
 if(action==='close'){$('#w-dialog').close();return;}
 if(action==='lang'){language=language==='ka'?'en':'ka';try{localStorage.setItem('dlg-language',language);}catch{}location.reload();return;}
 if(action==='google'){await run(b,async()=>{if(!sb)throw Error('Auth unavailable');await checked(sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+(admin?'/admin/inbox/':'/client/')}}));});return;}
 if(action==='logout'){await run(b,async()=>{await checked(sb.auth.signOut());session=null;activeUid=null;login();});return;}
 if(b.dataset.select){selected=requests.find(r=>r.id===b.dataset.select);detailTab='overview';renderList();await run(b,detail);return;}
 if(b.dataset.tab){detailTab=b.dataset.tab;renderDetail();return;}
 if(action==='new'){openIntake();return;}if(action==='pricing'){pricing();return;}
 if(action==='add-item'||b.dataset.editItem){editItem(b.dataset.editItem);return;}
 if(action==='add-doc'||b.dataset.editDoc){editDoc(b.dataset.editDoc);return;}
 if(b.dataset.approveDoc){approveDoc(b.dataset.approveDoc);return;}
 if(b.dataset.downloadDoc){const d=documents.find(d=>d.id===b.dataset.downloadDoc);download('DLG-'+d.kind+'-v'+d.version+'.txt',d.title+'\n\n'+d.body);return;}
 if(b.dataset.downloadFile){await run(b,async()=>{const blob=await checked(sb.storage.from('dlg-matter-files').download(selected.id+'/'+b.dataset.downloadFile));download(b.dataset.downloadFile.replace(/^[a-f0-9-]{36}--/,''),blob);});return;}
 if(b.dataset.publishDoc){const d=documents.find(d=>d.id===b.dataset.publishDoc);if(!d.published&&d.body.includes('[დასაზუსტებელია]')){notice(say('ჯერ შეავსეთ ყველა მოსანიშნი ადგილი და გადაამოწმეთ დოკუმენტი.','Complete every placeholder and review the document first.'),true);return;}await run(b,async()=>{await checked(sb.from('dlg_documents').update({published:!d.published}).eq('id',d.id).eq('version',d.version).select().single());await detail();notice(say('დოკუმენტის გაზიარება განახლდა.','Document sharing updated.'));});return;}
 if(action==='seed'){await run(b,async()=>{const pack=createDeliveryPack(selected);await checked(sb.rpc('dlg_seed_delivery',{rid:selected.id,...pack}));await detail();notice(say('სამუშაო პაკეტი შექმნილია. დოკუმენტები სამუშაო პროექტებად ინახება.','Delivery pack created. Documents remain drafts.'));});return;}
 if(action==='refresh'){await run(b,refresh);return;}if(action==='due'){await run(b,dueWork);return;}
 if(action==='bundle'){download('DLG-delivery-'+selected.id.slice(0,8)+'.json',JSON.stringify({exported_at:new Date().toISOString(),request:selected,items,documents,events,approvals:approvals.filter(a=>documents.some(d=>d.id===a.document_id))},null,2),'application/json');return;}
 if(action==='export'){const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';download('DLG-matters.csv','\uFEFF'+[['ID','Title','Company','Service','Status','Created'],...requests.map(r=>[r.id,r.title,r.company_name,r.service_label,r.status,r.created_at])].map(row=>row.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
}
async function boot(){frame();try{if(!window.supabase)throw Error('SDK not loaded');sb=window.supabase.createClient(URL,KEY);const r=await checked(sb.auth.getSession());session=r.session;await showSession();sb.auth.onAuthStateChange((event,next)=>{session=next;if(!next){if($('#w-dialog').open)$('#w-dialog').close();login();activeUid=null;}else if(event==='SIGNED_IN'&&activeUid!==next.user.id)setTimeout(()=>showSession().catch(fail),0);});}catch{login();notice(say('სივრცის ჩატვირთვა ვერ მოხერხდა. განაახლეთ გვერდი ან მოგვწერეთ ელფოსტით.','Workspace could not load. Refresh or contact us by email.'),true);}}
boot();
