-- Integration test. All fixtures and changes roll back; no client data is read.
begin;
create temporary table dlg_test_ids(a uuid,b uuid,staff uuid,rid uuid,did uuid);
insert into dlg_test_ids values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),null,null);
grant all on dlg_test_ids to authenticated,anon;
insert into auth.users(id,email) select a,'dlg-fixture-a@example.invalid' from dlg_test_ids union all select b,'dlg-fixture-b@example.invalid' from dlg_test_ids union all select staff,'dlg-fixture-staff@example.invalid' from dlg_test_ids;
insert into public.dlg_admin_users(email) values('dlg-fixture-staff@example.invalid');
select set_config('request.jwt.claims',json_build_object('sub',a,'email','dlg-fixture-a@example.invalid','role','authenticated')::text,true) from dlg_test_ids;
set local role authenticated;
update dlg_test_ids set rid=public.dlg_submit_request('{"title":"DLG transaction test","description":"A test brief for the delivery workflow","service_slug":"product","service_label":"Test","preferred_language":"ka","intake":{"market":"Georgia"}}');
do $$begin if (select count(*) from public.dlg_client_request_events where request_id=(select rid from dlg_test_ids))<>1 then raise exception 'Atomic intake failed';end if;end$$;
select set_config('request.jwt.claims',json_build_object('sub',b,'email','dlg-fixture-b@example.invalid','role','authenticated')::text,true) from dlg_test_ids;
do $$begin if exists(select 1 from public.dlg_client_requests where id=(select rid from dlg_test_ids)) then raise exception 'Cross-client request leak';end if;begin perform public.dlg_seed_delivery((select rid from dlg_test_ids),'[]','[]');raise exception 'Client can initialise admin delivery';exception when raise_exception then if sqlerrm='Client can initialise admin delivery' then raise;end if;end;end$$;
select set_config('request.jwt.claims',json_build_object('sub',staff,'email','dlg-fixture-staff@example.invalid','role','authenticated')::text,true) from dlg_test_ids;
select public.dlg_seed_delivery((select rid from dlg_test_ids),'[{"kind":"task","title":"Shared task","shared":true},{"kind":"check","title":"Internal task","shared":false}]','[{"kind":"proposal","title":"Proposal","body":"A reviewed proposal with agreed scope and fee."}]');
update dlg_test_ids set did=(select id from public.dlg_documents where request_id=dlg_test_ids.rid);
select set_config('request.jwt.claims',json_build_object('sub',a,'email','dlg-fixture-a@example.invalid','role','authenticated')::text,true) from dlg_test_ids;
do $$begin if (select count(*) from public.dlg_delivery_items where request_id=(select rid from dlg_test_ids))<>1 then raise exception 'Internal task leak';end if;if exists(select 1 from public.dlg_documents where id=(select did from dlg_test_ids)) then raise exception 'Draft document leak';end if;update public.dlg_client_requests set status='completed' where id=(select rid from dlg_test_ids);if found then raise exception 'Client can change delivery status';end if;end$$;
select set_config('request.jwt.claims',json_build_object('sub',staff,'email','dlg-fixture-staff@example.invalid','role','authenticated')::text,true) from dlg_test_ids;
update public.dlg_documents set published=true where id=(select did from dlg_test_ids);
select public.dlg_update_progress((select rid from dlg_test_ids),'reviewing',1);
select set_config('request.jwt.claims',json_build_object('sub',a,'email','dlg-fixture-a@example.invalid','role','authenticated')::text,true) from dlg_test_ids;
insert into public.dlg_document_approvals(document_id,user_id,version,body_snapshot) select d.id,auth.uid(),d.version,d.body from public.dlg_documents d where d.id=(select did from dlg_test_ids);
insert into storage.objects(bucket_id,name,owner_id) select 'dlg-matter-files',rid::text||'/fixture.txt',a::text from dlg_test_ids;
do $$begin if not exists(select 1 from public.dlg_document_approvals where document_id=(select did from dlg_test_ids)) then raise exception 'Approval failed';end if;end$$;
select set_config('request.jwt.claims',json_build_object('sub',b,'email','dlg-fixture-b@example.invalid','role','authenticated')::text,true) from dlg_test_ids;
do $$begin if exists(select 1 from public.dlg_documents where id=(select did from dlg_test_ids)) then raise exception 'Other client document leak';end if;if exists(select 1 from public.dlg_document_approvals where document_id=(select did from dlg_test_ids)) then raise exception 'Other client approval leak';end if;if exists(select 1 from storage.objects where name=(select rid::text||'/fixture.txt' from dlg_test_ids)) then raise exception 'Other client file leak';end if;end$$;
select set_config('request.jwt.claims',json_build_object('sub',staff,'email','dlg-fixture-staff@example.invalid','role','authenticated')::text,true) from dlg_test_ids;
update public.dlg_documents set body='Revised proposal; requires fresh client review.' where id=(select did from dlg_test_ids);
do $$begin if not exists(select 1 from public.dlg_documents where id=(select did from dlg_test_ids) and version=2 and not published) then raise exception 'Document version/unpublish failed';end if;if not exists(select 1 from public.dlg_document_approvals where document_id=(select did from dlg_test_ids) and version=1 and body_snapshot='A reviewed proposal with agreed scope and fee.') then raise exception 'Approval snapshot changed';end if;end$$;
reset role;
rollback;
select 'PASS: atomic intake, client isolation, admin workflow, draft visibility, document revision, immutable approval snapshot and file isolation' as result;
