import fs from 'node:fs';
import path from 'node:path';
import {validateResources,renderBody,esc,topics,formats} from '../resources/resource-model.mjs';
const out=process.env.SITE_OUTPUT||'dist';
const siteUrl=(process.env.SITE_URL||'https://lukaswebsite.vercel.app').replace(/\/+$/,'');
if(!['dist','test-dist'].includes(out))throw new Error('Unsupported output directory');
const all=validateResources(JSON.parse(fs.readFileSync('_data/resources.json','utf8')));
const today=new Date().toISOString().slice(0,10);
const rows=all.filter(r=>r.status==='published'&&r.date<=today).sort((a,b)=>b.date.localeCompare(a.date));
fs.rmSync(out,{recursive:true,force:true}); fs.mkdirSync(out,{recursive:true});
for(const file of ['styles.css','script.js','favicon.svg'])fs.copyFileSync(file,path.join(out,file));
fs.cpSync('assets',path.join(out,'assets'),{recursive:true}); fs.cpSync('admin',path.join(out,'admin'),{recursive:true});
fs.mkdirSync(path.join(out,'resources'),{recursive:true});
for(const file of ['resources.js','resource-model.mjs'])fs.copyFileSync('resources/'+file,out+'/resources/'+file);
const tr=(ka,en)=>`data-en="${esc(en||ka)}"`;
const link=(p)=>p; // Root-relative paths on the primary Vercel domain.
const resolveLiquid=s=>s.replace(/{{\s*'([^']+)'\s*\|\s*relative_url\s*}}/g,(_,p)=>link(p)).replace(/{% unless page.section == 'services' %}([\s\S]*?){% endunless %}/g,'$1');
const header=resolveLiquid(fs.readFileSync('_includes/resource-header.html','utf8'));
const footer=resolveLiquid(fs.readFileSync('_includes/resource-footer.html','utf8'));
function shell({title,title_en,summary,summary_en,url,content,image='',article=false,noindex=false}){
 const canonical=siteUrl+url;
 return `<!doctype html><html lang="ka"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Digital Law Georgia</title><meta name="description" content="${esc(summary)}">${noindex?'<meta name="robots" content="noindex,nofollow">':'<link rel="canonical" href="'+canonical+'">' }<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(summary)}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:url" content="${canonical}">${image?`<meta property="og:image" content="${esc(image.startsWith('/')?siteUrl+image:image)}">`:''}<link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css?v=20260922-brand-final"><link rel="preload" as="font" type="font/woff2" href="/assets/noto-georgian.woff2" crossorigin><script src="/script.js?v=20260922-ux" defer></script><script src="/resources/resources.js?v=20260922-ux" defer></script></head><body class="resource-page" data-default-language="en" data-title-ka="${esc(title)} — Digital Law Georgia" data-title-en="${esc(title_en||title)} — Digital Law Georgia" data-description-ka="${esc(summary)}" data-description-en="${esc(summary_en||summary)}"><a class="skip-link" href="#main" data-en="Skip to content">მთავარ შინაარსზე გადასვლა</a>${header}${content}${footer}</body></html>`;
}
function card(r,preview=false){
 return `<article class="resource-card visual-resource" data-resource-card data-kind="${r.format}" data-topic="${r.topic}" data-search="${esc([r.title,r.title_en,r.summary,r.summary_en,r.audience,r.audience_en].join(' '))}"><a class="resource-cover" href="/resources/${r.slug}/" data-site-link tabindex="-1" aria-hidden="true"><img src="${esc(r.cover)}" alt="" loading="lazy" width="1200" height="800"></a><div class="resource-card-copy"><div class="resource-card-top"><span class="resource-type" ${tr(formats[r.format].ka,formats[r.format].en)}>${esc(formats[r.format].ka)}</span><span class="resource-reading" ${tr(`${Math.max(2,Math.ceil(r.body.split(/\s+/).length/110))} წუთი`,`${Math.max(2,Math.ceil((r.body_en||r.body).split(/\s+/).length/180))} min`)}>${Math.max(2,Math.ceil(r.body.split(/\s+/).length/110))} წუთი</span></div><h3><a href="/resources/${r.slug}/" data-site-link ${tr(r.title,r.title_en)}>${esc(r.title)}</a></h3><p ${tr(r.summary,r.summary_en)}>${esc(r.summary)}</p><div class="resource-card-bottom"><span ${tr(topics[r.topic].ka,topics[r.topic].en)}>${esc(topics[r.topic].ka)}</span><span aria-hidden="true">↗</span></div></div></article>`;
}
let home=fs.readFileSync('index.html','utf8').replaceAll('https://lukaswebsite.vercel.app',siteUrl);
home=home.replace('<!-- practical-resource-cards -->',rows.filter(r=>r.featured).slice(0,3).map(r=>card(r,true)).join(''));
home=home.replace('A space for articles, practical guides and official sources on technology and business law.','Practical guides to help you review contracts, assess suppliers and introduce technology.').replace('სტატიების, პრაქტიკული გზამკვლევებისა და ოფიციალური წყაროების სივრცე ტექნოლოგიებისა და ბიზნესის სამართლებრივ საკითხებზე.','პრაქტიკული გზამკვლევები ხელშეკრულებების შეფასების, მომწოდებლების შერჩევისა და ტექნოლოგიების დანერგვისთვის.').replaceAll('?v=20260917-ai','?v=20260919-resources');
fs.writeFileSync(out+'/index.html',home);
const controls=`<div class="resource-controls" id="resource-controls" hidden><div class="resource-search-row"><div><label for="resource-search" data-en="Search resources">რესურსის ძიება</label><input id="resource-search" type="search" maxlength="120" placeholder="მოძებნეთ თემა ან საკვანძო სიტყვა" data-en-placeholder="Search a topic or keyword"></div><div><label for="resource-topic" data-en="Topic">თემა</label><select id="resource-topic"><option value="all" data-en="All topics">ყველა თემა</option>${Object.entries(topics).map(([k,v])=>`<option value="${k}" ${tr(v.ka,v.en)}>${v.ka}</option>`).join('')}</select></div></div><div class="resource-filter-row"><div class="resource-tabs" role="group" aria-label="მასალის ტიპი" data-en-aria="Resource type"><button type="button" data-resource-type="all" aria-pressed="true" data-en="All resources">ყველა</button>${Object.entries(formats).map(([k,v])=>`<button type="button" data-resource-type="${k}" aria-pressed="false" ${tr(v.ka,v.en)}>${v.ka}</button>`).join('')}</div><p id="resource-count" role="status" aria-live="polite"></p></div></div>`;
const hub=`<main id="main"><section class="resource-hero"><div class="container"><a class="resource-back" href="/" data-site-link data-en="← Home">← მთავარი</a><p class="eyebrow" data-en="PRACTICAL RESOURCES">პრაქტიკული რესურსები</p><h1 data-en="A useful starting point.">ცოდნა, რომელსაც საქმეში გამოიყენებთ.</h1><p class="resource-hero-description" data-en="Clear explanations, focused questions and practical steps for the decisions your business faces.">გასაგები განმარტებები, კონკრეტული კითხვები და პრაქტიკული ნაბიჯები თქვენი ბიზნესის ყოველდღიური გადაწყვეტილებებისთვის.</p></div></section><section class="resource-library"><div class="container">${controls}<div class="resource-grid" id="resource-grid">${rows.map(r=>card(r)).join('')}</div><div class="resource-empty" id="resource-empty" hidden><h2 id="resource-empty-title"></h2><p id="resource-empty-description"></p><button type="button" id="resource-reset" class="button button-secondary" data-en="Show all resources">ყველა რესურსი</button></div></div></section><section class="resource-help"><div class="container"><div><h2 data-en="Need help applying this to your business?">გჭირდებათ დახმარება კონკრეტულ საკითხზე?</h2><p data-en="Tell us what you are working on and where you need legal input.">მოგვწერეთ, რაზე მუშაობთ და რაში გჭირდებათ იურიდიული მხარდაჭერა.</p></div><a class="button button-primary" href="/#contact" data-site-link data-en="Discuss your matter">განვიხილოთ თქვენი საკითხი</a></div></section></main>`;
fs.writeFileSync(out+'/resources/index.html',shell({title:'პრაქტიკული რესურსები',title_en:'Practical resources',summary:'პრაქტიკული გზამკვლევები ხელშეკრულებების, მონაცემებისა და ხელოვნური ინტელექტის გამოყენების შესახებ.',summary_en:'Practical guides on contracts, business data and using AI.',url:'/resources/',content:hub}));
for(const r of rows){
 const content=`<main id="main"><article class="article-page container"><a class="resource-back" href="/resources/" data-site-link data-en="← All resources">← ყველა რესურსი</a><header class="article-header"><p class="eyebrow" ${tr(topics[r.topic].ka,topics[r.topic].en)}>${topics[r.topic].ka}</p><h1 ${tr(r.title,r.title_en)}>${esc(r.title)}</h1><p class="article-summary" ${tr(r.summary,r.summary_en)}>${esc(r.summary)}</p><div class="article-meta"><span ${tr(r.author,r.author_en)}>${esc(r.author)}</span><time datetime="${r.date}">${r.date.split('-').reverse().join('.')}</time><span ${tr(r.audience,r.audience_en)}>${esc(r.audience)}</span></div></header><img class="article-cover" src="${esc(r.cover)}" alt="${esc(r.cover_alt)}" data-en-alt="${esc(r.cover_alt_en||r.cover_alt)}" width="1200" height="800"><div class="article-tools"><button type="button" class="text-link" data-print-resource data-en="Print / save PDF">ბეჭდვა / PDF-ად შენახვა</button><button type="button" class="text-link" data-copy-resource data-en="Copy link">ბმულის კოპირება</button><span data-copy-status role="status"></span></div>${r.body_en?'':`<p class="translation-note" data-en="This resource is currently available in Georgian.">მასალის ტექსტი ამჟამად ქართულ ენაზეა.</p>`}<div class="article-content" lang="ka" ${r.body_en?'data-content-language="ka"':''}>${renderBody(r.body)}</div>${r.body_en?`<div class="article-content" lang="en" data-content-language="en" hidden>${renderBody(r.body_en)}</div>`:''}${r.sources.length?`<aside class="resource-sources"><h2 data-en="Further reading">დამატებითი საკითხავი</h2><ul>${r.sources.map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a></li>`).join('')}</ul></aside>`:''}<div class="article-contact"><h2 data-en="Let's discuss your situation">განვიხილოთ თქვენი საკითხი</h2><p data-en="For advice on a particular contract, supplier or project, send a short enquiry.">კონკრეტულ ხელშეკრულებაზე, მომწოდებელზე ან პროექტზე კონსულტაციისთვის მოკლედ მოგვწერეთ.</p><a class="button button-primary" href="/?service=${r.topic==='contracts'?'contracts':'ai-data'}#contact" data-site-link data-en="Get in touch">დაგვიკავშირდით</a></div></article><section class="section related-resources"><div class="container"><h2 data-en="You may also find useful">სხვა პრაქტიკული მასალები</h2><div class="resource-preview-grid">${rows.filter(x=>x.slug!==r.slug).slice(0,3).map(x=>card(x)).join('')}</div></div></section></main>`;
 fs.mkdirSync(`${out}/resources/${r.slug}`,{recursive:true});fs.writeFileSync(`${out}/resources/${r.slug}/index.html`,shell({...r,url:`/resources/${r.slug}/`,content,image:r.cover,article:true}));
}
// Render the existing AI service page so its Liquid source is never served by Vercel.
let ai=fs.readFileSync('services/ai/index.html','utf8');ai=resolveLiquid(ai.replace(/^---\n[\s\S]*?\n---\n/,''));
fs.mkdirSync(out+'/services/ai',{recursive:true});fs.writeFileSync(out+'/services/ai/index.html',shell({title:'ხელოვნური ინტელექტი და სამართალი',title_en:'AI and the law',summary:'ხელოვნური ინტელექტის სამართლებრივი მხარდაჭერა ბიზნესისთვის.',summary_en:'Legal support for businesses building or using AI.',url:'/services/ai/',content:ai}).replace('href="/resources/" data-site-link aria-current="page"','href="/resources/" data-site-link'));

const servicePages=[
  {slug:'contracts',title:'კომერციული და ტექნოლოგიური ხელშეკრულებები',title_en:'Commercial & technology contracts',summary:'ხელშეკრულებების მომზადება, შემოწმება და მოლაპარაკების მხარდაჭერა ბიზნესისთვის.',summary_en:'Contract drafting, review and negotiation support for businesses.'},
  {slug:'ongoing-legal-support',title:'ყოველთვიური იურიდიული მომსახურება',title_en:'Ongoing legal counsel',summary:'მიმდინარე იურიდიული მხარდაჭერა კომპანიებისთვის შეთანხმებული ფარგლებით.',summary_en:'Ongoing legal support for companies within an agreed scope.'},
  {slug:'data-protection',title:'პერსონალური მონაცემების დაცვა',title_en:'Data protection for business',summary:'პერსონალური მონაცემების დამუშავების შეფასება, დოკუმენტები და დანერგვის მხარდაჭერა.',summary_en:'Practical data protection assessment, documentation and implementation support.'},
  {slug:'ecommerce',title:'ელექტრონული კომერციის სამართლებრივი მხარდაჭერა',title_en:'E-commerce legal support',summary:'სამართლებრივი მხარდაჭერა ონლაინგაყიდვების, ციფრული პროდუქტებისა და მომხმარებელთან ურთიერთობისთვის.',summary_en:'Legal support for online sales, digital products and customer-facing processes.'},
  {slug:'georgia-market-entry',title:'საქართველოში საქმიანობის სამართლებრივი მხარდაჭერა',title_en:'Doing business in Georgia — local legal counsel',summary:'ინგლისურენოვანი ადგილობრივი სამართლებრივი მხარდაჭერა საქართველოში საქმიანობის მსურველი უცხოური ბიზნესისთვის.',summary_en:'English-language local legal counsel for foreign businesses entering or operating in Georgia.'}
];
for(const s of servicePages){
  let content=fs.readFileSync(`services/${s.slug}/index.html`,'utf8');
  content=resolveLiquid(content.replace(/^---\n[\s\S]*?\n---\n/,''));
  fs.mkdirSync(`${out}/services/${s.slug}`,{recursive:true});
  fs.writeFileSync(`${out}/services/${s.slug}/index.html`,shell({...s,url:`/services/${s.slug}/`,content}).replace('href="/resources/" data-site-link aria-current="page"','href="/resources/" data-site-link'));
}
fs.writeFileSync(out+'/404.html',shell({title:'გვერდი ვერ მოიძებნა',title_en:'Page not found',summary:'',url:'/404.html',noindex:true,content:'<main id="main" class="container article-page"><h1 data-en="Page not found">გვერდი ვერ მოიძებნა</h1><p data-en="The page you requested does not exist or has moved.">მოთხოვნილი გვერდი არ არსებობს ან მისამართი შეიცვალა.</p><a class="button button-primary" href="/" data-site-link data-en="Return home">მთავარ გვერდზე დაბრუნება</a></main>'}).replace(' aria-current="page"',''));
fs.writeFileSync(out+'/robots.txt',`User-agent: *\nDisallow: /admin/\nSitemap: ${siteUrl}/sitemap.xml\n`);
fs.writeFileSync(out+'/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/','/resources/','/services/ai/',...servicePages.map(s=>`/services/${s.slug}/`),...rows.map(r=>`/resources/${r.slug}/`)].map(p=>`<url><loc>${siteUrl}${p}</loc></url>`).join('')+'</urlset>');
console.log(`Built ${rows.length} published resources. Drafts and archived content excluded.`);
